# Generated by cucumber-sinatra. (2015-09-09 10:22:43 -0430)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'init.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = PitApp

class PitAppWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  PitAppWorld.new
end
